# Digital Forms API Application properties. 
# Note: Values prefixed with $ are externalized values and must be set via OS Secrets or if running locally 
# using environmental variables with same name.      
    
management:
  endpoint:
    beans:
      cache:
        # Actuator bean time to live. Inhibits caching of 'No param' endpoints.
        time-to-live: 10s
    #Actuator Health Endpoint Configuration    
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        # Actuator endpoint exposure
        include: health
        
server:
  port: 8082
  servlet:
    context-path: /digitalforms-viirp/v1
    
# VIPS ORDS CLIENT properties
vips:
  rest-api:
    url: ${DIGITALFORMS_VIPSAPI_URL:}
    password: ${DIGITALFORMS_VIPSAPI_PASSWORD:}
    username: ${DIGITALFORMS_VIPSAPI_USERNAME:}
    credentials: 
      guid: ${DIGITALFORMS_VIPSAPI_CREDS_GUID:}
      user: ${DIGITALFORMS_VIPSAPI_CREDS_USER:}
      displayname: ${DIGITALFORMS_VIPSAPI_CREDS_DISPLAYNAME:}
    timeout: ${DIGITALFORMS_VIPSAPI_TIMEOUT:2000}
    retry:
      # The maximum number of retry attempts to allow
      count: ${DIGITALFORMS_VIPSAPI_RETRY_COUNT:3}
      # The Duration of the fixed delays
      delay: ${DIGITALFORMS_VIPSAPI_RETRY_DELAY:5}
      
  client:
    basePath: ${DIGITALFORMS_VIPSORDS_BASEPATH}
    password: ${DIGITALFORMS_VIPSORDS_PASSWORD}
    username: ${DIGITALFORMS_VIPSORDS_USER}
    
digitalforms:
  client:
    basePath: ${DIGITALFORMS_ORDS_BASEPATH}
    password: ${DIGITALFORMS_ORDS_PASSWORD}
    username: ${DIGITALFORMS_ORDS_USER}
    
  basic-auth:
    user: ${DIGITALFORMS_BASICAUTH_USER:}
    password: ${DIGITALFORMS_BASICAUTH_PASSWORD:}
    
# Spring Doc Swagger-UI enable / disable    
springdoc:
    swagger-ui:
      enabled: ${DIGITALFORMS_SWAGGER_ENABLED:false}
