apiVersion: template.openshift.io/v1
kind: Template
metadata: {}
parameters:
- name: NAME
  value: digitalforms-viirp-api
- name: NAMESPACE
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  value: 200m
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  value: 400m
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  value: 200Mi
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  value: 500Mi
- name: IMAGE_NAMESPACE
- name: IMAGE_TAG
  required: true
- name: SECRET1_NAME
- name: SECRET2_NAME
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    namespace: ${NAMESPACE}
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${NAME}:${IMAGE_TAG}
          name: ${NAME}
          resources:
            limits:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          envFrom:
          - secretRef:
              name: ${SECRET1_NAME}
          - secretRef:
              name: ${SECRET2_NAME}
          ports:
            - containerPort: 8082
              protocol: TCP
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    namespace: ${NAMESPACE}
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    maxReplicas: 2
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: Deployment
      name: ${NAME}
    targetCPUUtilizationPercentage: 85
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    path: "/"
    port:
      targetPort: 8082-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
