kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Build template for an openjdk11-openshift based app.
    tags: vips-api-image
    iconClass: icon-java
  name: ${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        shared: "true"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        component: ${NAME}
        name: ${NAME}
    spec:
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        # sourceSecret:
        #   name: ${GIT_REPO_DEPLOY_KEY}
      completionDeadlineSeconds: 1440
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 1
          memory: 4Gi
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      # triggers:
      #   - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.  You should keep this as default unless your know what your doing.
    required: true
    # value: vips-api
  - name: VERSION
    displayName: Application version number
    description: Application version number
    required: true
    # value: "1.1"
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo, don't use the this default unless your just experimenting.
    required: true
  - name: GIT_REPO_DEPLOY_KEY
    displayName: Git Repo Deploy Key
    description: The Deploy Key for ssh access to  your GIT repo.
    required: true
    # value: vips-api-repo-key
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
