apiVersion: v1
kind: Template
metadata: {}
parameters:
- name: NAME
  # value: vips
- name: COMPONENT
  # value: restapi
- name: PHASE
- name: SUFFIX
  # value: -dev
# - name: VERSION
- name: HOST
- name: LOG_LEVEL
  value: 'INFO'
- name: URL_SUFFIX
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
- name: NAMESPACE
  # value: 
- name: BUILD_VERSION
- name: BUILD_CONFIG_SUFFIX
- name: IMAGE_NAMESPACE
- name: SECRET1_NAME
- name: SECRET2_NAME
# - name: IMAGE_NAME
#   value: 
- name: IMAGE_TAG
  # value: "1.1"
- name: API_VERSION
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    namespace: ${NAMESPACE}
    labels:
      app: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
    name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${NAME}-image:${BUILD_CONFIG_SUFFIX}-${BUILD_VERSION}
          name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
          resources:
            limits:
              cpu: 80m
              memory: 96Mi
            requests:
              cpu: 60m
              memory: 64Mi
          envFrom:
          - secretRef:
              name: ${SECRET1_NAME}
          - secretRef:
              name: ${SECRET2_NAME}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    namespace: ${NAMESPACE}
    labels: null
    name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
  spec:
    maxReplicas: 2
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: Deployment
      name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
    targetCPUUtilizationPercentage: 85
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
    namespace: ${NAMESPACE}
  spec:
    # host: ${NAME}-${COMPONENT}${SUFFIX}
    path: ""
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}-${COMPONENT}${SUFFIX}-${API_VERSION}
      weight: 100
    wildcardPolicy: None
