name: CI Checks for API

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn -B test --file pom.xml
#    - name: Publish Test Report
#      if: ${{ always() }}
#      uses: scacap/action-surefire-report@v1
